name: chainmetric
description: Mobile client application for the IoT enabled blockchain supply chain controlled by sensor requirements system.
publish_to: 'none'
version: 2.3.0-1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Project:
  flutter:
    sdk: flutter
  # Dart packages:
  tuple: ^2.0.0
  yaml: ^3.1.0
  flutter_isolate: ^2.0.0
  grpc: ^3.0.1
  path_provider: ^2.0.2
  # Flutter add-ons:
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  global_configuration: ^2.0.0-nullsafety.1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  rect_getter: ^1.0.0
  # UI components
  multi_select_flutter: ^4.0.0
  numberpicker: ^2.1.1
  qr_code_scanner: ^0.5.2
  modal_bottom_sheet: ^2.0.0
  overlay_screen: ^1.2.0+1-nullsafety.0
  loading_animations: ^2.2.0 # TODO: remove in favor of `flutter_spinkit`
  charts_flutter: ^0.11.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  place_picker: ^0.9.19-nullsafety
  # Platform functionality:
  permission_handler: ^8.1.4+2
  geolocator: ^7.4.0
  geocoding: ^2.0.0
  flutter_reactive_ble: ^3.1.1+1
  talos:
    path: ../talos

dev_dependencies:
  build_runner: ^2.1.1
  lint: ^1.5.3
  json_serializable: ^4.1.4


flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/certs/
    - assets/config.yaml
    - assets/connection.yaml
