name: iotchain
description: Mobile client application for the IoT enabled blockchain supply chain controlled by sensor requirements system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.27
  file_picker: ^1.3.7
  dart_json_mapper: ^1.2.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/data/organizations.json
    - assets/data/asset_types.json
