name: chainmetric
description: Mobile client application for the IoT enabled blockchain supply chain controlled by sensor requirements system.
publish_to: 'none'
version: 2.3.0-1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: any
  reflectable: ^3.0.2
  permission_handler: ^7.1.0
  streams_channel: ^0.2.3
  global_configuration: 2.0.0-nullsafety.1
  yaml: ^3.1.0
  flutter_blue: ^0.8.0
  geolocator: ^7.0.3
  path_provider: ^2.0.1
  dart_json_mapper: ^2.0.9
  file_picker: ^1.3.7
  cupertino_icons: ^1.0.2
  multi_select_flutter: ^2.1.0
  numberpicker: ^2.1.1
  qr_code_scanner: ^0.3.5
  modal_bottom_sheet: ^2.0.0
  overlay_screen: ^1.2.0+1
  loading_animations: ^2.1.0
  flutter_svg: ^0.22.0
  charts_flutter: ^0.10.0
  smooth_page_indicator: ^0.2.3
  rect_getter: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/config.yaml
